language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: install
      name: "Install dependencies"
      script: npm install
    - stage: test
      name: "Run unit tests"
      script: npm run test
    - script: npm run lint
      name: "Run linter"
    - stage: build
      name: "Make build"
      script: npm run build
    - stage: before_deploy
      name: "Give permissions"
      script: chmod +x deploy.sh
    - stage: deploy
      script: ./deploy.sh
      name: "Deploy to GitHub Pages"
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master


stages:
  - install
  - test
  - build
  - before_deploy
  - deploy

